### PR TITLE
added placeholder image when an item doesn't have a photo

### PR DESCRIPTION
**Pull request by EladWeinson**
# Description

Fix for #3 
Fixed for the home screen and a single item screen

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @EladWeinson, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by EladWeinson** [comment]
Screen Shot 2022-08-09 at 13 37 16

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @EladWeinson! You're now able to merge the PR.

**Pull request merged**
